spring:
  servlet:
    multipart:
      enabled: false
  datasource:
    url: jdbc:sqlite:airshare.db
    driver-class-name: org.sqlite.JDBC

hxy:
  print:
    file : /upload-file
    absolute-file-path:

logging:
  level:
    root: info
    hxy.dragon: debug
server:
  port: 8888
