spring:
  servlet:
    multipart:
      enabled: false
      location: /media/data/data/tmp/upload # 解决 linux系统上占用 /tmp文件夹问题。https://blog.csdn.net/jianxia801/article/details/99671263
  datasource:
    url: jdbc:sqlite:airshare.db
    driver-class-name: org.sqlite.JDBC

hxy:
  print:
    file: /upload-file
    absolute-file-path: /media/data/data/air-share/air-share # 如果绝对地址为空，那么就会采用当前用户下的一个默认地址，具体见代码
#    absolute-file-path: /mnt/resource/data/air-share # 如果绝对地址为空，那么就会采用当前用户下的一个默认地址，具体见代码

logging:
  level:
    root: info
    hxy.dragon: debug
server:
  port: 8888

mybatis-plus:
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# https://gitee.com/huoyo/ko-time
ko-time:
  pointcut: execution(public * hxy.dragon..*.*(..))
  context-path: https://files.cupb.top/api # 注意这个走了nginx，所以需要自定义下，否则会404 https://gitee.com/huoyo/ko-time/issues/I4XVRI