spring:
  application:
    name: AIR-SHARE
  servlet:
    multipart:
      enabled: false
  datasource:
    url: jdbc:sqlite:airshare.db
    driver-class-name: org.sqlite.JDBC
  profiles:
    active: prod

hxy:
  print:
    file: /upload-file
    absolute-file-path:

logging:
  level:
    root: info
    hxy.dragon: debug
server:
  port: 8888
#  address: 0.0.0.0 # 这里不会影响局域网访问
# 日志邮件报警
email:
  username: aohanhongzhi@qq.com
  password: vtrxapjtpcivdbcb
  default-encoding: UTF-8
  host: smtp.qq.com
  from: aohanhongzhi@qq.com
  to: aohanhongzhi@qq.com

info:
  build:
    artifact: hxy.dragon
    name: base-server
    version: 0.0.11_20200831
    description: base-server，prod环境
    current: 当前第2001次启动

# https://gitee.com/huoyo/ko-time
ko-time:
  pointcut: execution(public * hxy.dragon..*.*(..))
#  context-path: http://localhost:8080/koTime