### 从数据库删除数据
DELETE {{host}}/file/deleteForDb?fileUuid=d41d8cd98f00b204e9800998ecf8427e


###
DELETE  http://file.bosch-smartlife.com/file/download?fileUuid=o_1gb9p2ato17a9j23tbgbpd9q0c


### 查询

# curl 'http://localhost:5173/api/file/list?pageNum=1&pageSize=20'
#  -H 'Accept: application/json, text/plain, */*'
#  -H 'Accept-Language: en-US,en;q=0.9'
#  -H 'Connection: keep-alive'
#  -H 'Content-Type: application/json'
#  -H 'Referer: http://localhost:5173/'
#  -H 'Sec-Fetch-Dest: empty'
#  -H 'Sec-Fetch-Mode: cors'
#  -H 'Sec-Fetch-Site: same-origin'
#  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.1722.68'
#  -H 'sec-ch-ua: "Chromium";v="112", "Microsoft Edge";v="112", "Not:A-Brand";v="99"'
#  -H 'sec-ch-ua-mobile: ?0'
#  -H 'sec-ch-ua-platform: "macOS"'
#  --compressed
# &searchValue=
GET {{host}}/file/list?pageNum=1&pageSize=20&searchValue=oop
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.9
Connection: keep-alive
Content-Type: application/json

###

GET {{host}}/build


###

POST {{host}}/auth/login
Content-Type: application/json

{"usernameOrEmail":"aohanhongzhi@qq.com","password":"Sigh,0404"}


###

curl 'http://localhost:8888/file/list?pageNum=1&pageSize=20' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'accept-language: zh,en;q=0.9,en-US;q=0.8,zh-CN;q=0.7' \
  -H 'authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJ0b2tlblR5cGUiOiJhY2Nlc3MiLCJ1c2VySWQiOjEsImVtYWlsIjoiYW9oYW5ob25nemhpQHFxLmNvbSIsInVzZXJuYW1lIjoiYW9oYW5ob25nemhpIiwic3ViIjoiYW9oYW5ob25nemhpIiwiaWF0IjoxNzU4NzA1NDE3LCJleHAiOjE3NTg3MTI2MTd9.1DjpIoslPGlW0t-K1xD4lEQMMsf_E6Xh4XaC2UYhTBiQQlgi_kbTnFJEo-wXt_QM' \
  -b 'JSESSIONID=FAB59A26E48D6CEFB2BC371A3F6A9B99' \
  -H 'priority: u=1, i' \
  -H 'referer: https://file.cupb.top/' \
  -H 'sec-ch-ua: "Chromium";v="140", "Not=A?Brand";v="24", "Microsoft Edge";v="140"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36 Edg/140.0.0.0' \
  -H 'x-env: development' \
  -H 'x-version: 1.0.0'